name: Load

on:
  pull_request:
    branches: [main, master]

jobs:
  load-test:
    name: load-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: grafana/setup-k6-action@v1
      - uses: grafana/run-k6-action@v1
        with:
          path: |
            ./k6_test.js
