name: Cache

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  test-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print current commit information
        run: |
          echo "Current commit SHA: ${{ github.sha }}"
          echo "Current run ID: ${{ github.run_id }}"

      - name: Restore cache
        id: cache-restore
        uses: actions/cache@v3
        with:
          path: ./cache
          key: cache-test-${{ runner.os }}
          restore-keys: |
            cache-test-${{ runner.os }}

      - name: Check cache status after restore
        run: |
          echo "Cache restored: ${{ steps.cache-restore.outputs.cache-hit == 'true' && 'Yes' || 'No' }}"
          mkdir -p ./cache
          if [ -f "./cache/commit_hash.txt" ]; then
            echo "Previous commit in cache: $(cat ./cache/commit_hash.txt)"
            echo "Last update timestamp: $(cat ./cache/last_update.txt)"
          else
            echo "No previous commit hash found in cache"
          fi

      - name: Update cache content
        run: |
          echo "Updating cache with current commit: ${{ github.sha }}"
          echo "Updating cache with current timestamp: $(date)"
          node -e "
            const fs = require('fs');
            fs.writeFileSync('./cache/commit_hash.txt', '${{ github.sha }}', 'utf8');
            fs.writeFileSync('./cache/last_update.txt', new Date().toString(), 'utf8');
            console.log('Files written successfully using fs.writeFileSync');
          "
          ls -la ./cache

      - name: Post-cache update status
        run: |
          echo "Files in cache directory after update:"
          ls -la ./cache
          echo "Current commit in cache file: $(cat ./cache/commit_hash.txt)"
          echo "Last update timestamp: $(cat ./cache/last_update.txt)"
