name: Go Example
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  contents: write
  deployments: write
  pull-requests: write

jobs:
  benchmark:
    name: Run Go benchmark example
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4
        with:
          path: main-repo

      - name: Checkout benchmark branch
        uses: actions/checkout@v4
        with:
          ref: yorkie-ci-benchmark
          path: benchmark-repo
        continue-on-error: true

      - name: Check previous benchmark results
        run: |
          if [ -d "benchmark-repo" ] && [ -f "benchmark-repo/output.txt" ]; then
            echo "Previous benchmark results found:"
            echo "----------------------------------------"
            cat benchmark-repo/output.txt
            echo "----------------------------------------"
          else
            echo "No previous benchmark results found."
          fi

      - uses: actions/setup-go@v4
        with:
          go-version: "stable"

      - name: Run benchmark
        run: |
          cd main-repo
          go test -bench 'BenchmarkFib' | tee output.txt

      - name: Save benchmark results
        run: |
          mkdir -p benchmark-repo
          cp main-repo/output.txt benchmark-repo/
          cd benchmark-repo

          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          if [ ! -d ".git" ]; then
            git init
            git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          fi

          git add output.txt
          TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          git diff --staged --quiet || git commit -m "Update benchmark results at $TIMESTAMP [skip ci]"
          git checkout -B yorkie-ci-benchmark
          git push -f origin yorkie-ci-benchmark

          echo "Benchmark results have been pushed to yorkie-ci-benchmark branch"
